Repository sul-dlss/preservation_catalog, pull requests merged in 2018-06, with the labels that each got.

#816 way to run M2C for single druid
  README.md
  Rakefile
  lib/audit/moab_to_catalog.rb
  spec/lib/audit/moab_to_catalog_spec.rb
Labels: needs review

#819 audit_results: tweak error messages
  app/services/audit_results.rb
Labels: needs review

#818 Update more timestamps in checksum validator
  app/services/checksum_validator.rb
  spec/services/checksum_validator_spec.rb
Labels: needs review

#825 only set ok status if all validations (incl CV) have passed
  app/services/moab_validation_handler.rb
  app/services/preserved_object_handler.rb
  spec/lib/audit/catalog_to_moab_instance_spec.rb
  spec/services/preserved_object_handler_check_exist_spec.rb
  spec/services/preserved_object_handler_confirm_version_spec.rb
  spec/services/preserved_object_handler_create_spec.rb
  spec/services/preserved_object_handler_update_version_spec.rb
  spec/services/shared_examples_preserved_object_handler.rb
Labels: needs review

#839 CV - ensure it is only for online pres_copies
  app/models/preserved_copy.rb
  app/services/checksum_validator.rb
  lib/audit/checksum.rb
  spec/lib/audit/checksum_spec.rb
  spec/services/checksum_validator_spec.rb
Labels: needs review

#851 Update our db/schema
  db/schema.rb
Labels: needs review

#852 Fix #844: Zip util outputs "errors" on STDOUT
  app/jobs/zipmaker_job.rb
  spec/jobs/zipmaker_job_spec.rb
Labels: needs review

#840 Use dor-workflow-service for rest calls
  Gemfile
  Gemfile.lock
  app/services/workflow_errors_reporter.rb
  config/initializers/dor_workflow_service.rb
  config/settings.yml
  spec/controllers/catalog_controller_spec.rb
  spec/lib/audit/catalog_to_moab_instance_spec.rb
  spec/lib/audit/checksum_spec.rb
  spec/lib/audit/moab_to_catalog_spec.rb
  spec/services/audit_results_spec.rb
  spec/services/checksum_validator_spec.rb
  spec/services/preserved_object_handler_check_exist_spec.rb
  spec/services/preserved_object_handler_confirm_version_spec.rb
  spec/services/preserved_object_handler_create_spec.rb
  spec/services/preserved_object_handler_spec.rb
  spec/services/preserved_object_handler_update_version_spec.rb
  spec/services/workflow_errors_reporter_spec.rb
Labels: needs review

#854 Make resque's rake tasks available
  lib/tasks/.keep
  lib/tasks/resque.rake
Labels: needs review

#856 [WIP] remove double logging and add druid in message
  Rakefile
  lib/audit/checksum.rb
  lib/audit/moab_to_catalog.rb
Labels: needs review

#838 Fix #728 profiler_spec: no rails, do cleanup, order independence
  lib/profiler.rb
  spec/lib/profiler_spec.rb
Labels: bug, needs review

#727 Audit module
  .rubocop.yml
  Rakefile
  app/lib/active_record_utils.rb
  app/lib/audit.rb
  app/lib/audit/catalog_to_moab.rb
  app/lib/audit/checksum.rb
  app/lib/audit/moab_to_catalog.rb
  lib/audit/catalog_to_moab.rb
  lib/audit/checksum.rb
  lib/audit/moab_to_catalog.rb
  spec/lib/audit/catalog_to_moab_class_spec.rb
  spec/lib/audit/catalog_to_moab_instance_spec.rb
  spec/lib/audit/checksum_spec.rb
  spec/lib/audit/moab_to_catalog_spec.rb
  spec/load_fixtures_helper.rb
Labels: blocking!, needs review, refactor

#859 Add Audit:: namespace to Checksum
  Rakefile
Labels: needs review

#853 Add Audit Check Usage via Console to README
  README.md
Labels: needs review

#862 Make resque:setup load :environment
  lib/tasks/resque.rake
Labels: needs review

#855 Fix zipmaker bugs and gaps
  app/jobs/zipmaker_job.rb
  app/models/druid_version_zip.rb
  spec/jobs/zipmaker_job_spec.rb
  spec/models/druid_version_zip_spec.rb
Labels: blocking!, needs review

#870 Rakefile: add Audit namespace to M2C and C2M rake tasks
  Rakefile
Labels: needs review

#871 Profiler oneliner
  app/lib/audit/catalog_to_moab.rb
  app/lib/audit/checksum.rb
  app/lib/audit/moab_to_catalog.rb
  lib/profiler.rb
  spec/lib/profiler_spec.rb
Labels: needs review

#836 M2C, C2M: ensure they are only for online pres_copies
  app/services/preserved_object_handler.rb
  spec/services/preserved_object_handler_spec.rb
Labels: needs review

#873 replace AR obj creation with more concise factory invocation
  spec/services/preserved_object_handler_spec.rb
Labels: needs review

#879 Queue should match region: us_west_2
  app/jobs/s3_west_delivery_job.rb
Labels: needs review

#880 pohandler: remove redundant check for online pres_copy
  app/services/preserved_object_handler.rb
Labels: needs review

#875 Update workflow to completed if PC.status is OK
  .rubocop.yml
  app/services/audit_results.rb
  app/services/workflow_errors_reporter.rb
  app/services/workflow_reporter.rb
  spec/lib/audit/checksum_spec.rb
  spec/services/audit_results_spec.rb
  spec/services/checksum_validator_spec.rb
  spec/services/workflow_errors_reporter_spec.rb
  spec/services/workflow_reporter_spec.rb
Labels: needs review

#881 line in between constants and first method, make string use in update…
  app/services/workflow_reporter.rb
Labels: needs review

#883 Follow-up removal of unnecessary method and attribute
  app/services/checksum_validator.rb
  spec/services/checksum_validator_spec.rb
Labels: needs review

#872 Add test to show sdk picking up credentials from files
  spec/fixtures/aws_credentials
  spec/lib/preservation_catalog/s3_spec.rb
Labels: needs review

#887 Endpoint.seed_archive_endpoints_from_config should set delivery class
  app/models/endpoint.rb
  config/settings/development.yml
  config/settings/test.yml
  spec/models/endpoint_spec.rb
Labels: needs review

#884 CV queue
  app/jobs/checksum_validation_job.rb
  app/models/endpoint.rb
  spec/factories/preserved_object.rb
  spec/jobs/checksum_validation_job_spec.rb
  spec/jobs/integration_spec.rb
  spec/models/endpoint_spec.rb
Labels: needs review

#898 Replace normalize_druid_name with more accurate validation
  app/models/preserved_object.rb
  db/migrate/20180511210539_noramlize_druid_name.rb
  spec/models/preserved_object_spec.rb
Labels: needs review

#908 Re-write #create_archive_preserved_copies
  app/models/preserved_object.rb
  spec/models/preserved_object_spec.rb
Labels: needs review

#896 Add `PreservedCopy#replicate!` with tests
  app/models/preserved_copy.rb
  spec/models/preserved_copy_spec.rb
Labels: needs review

#911 update dependencies
  Gemfile.lock
Labels: needs review

#916 Rakefile fun
  .rubocop.yml
  .simplecov
  README.md
  Rakefile
  app/lib/audit/moab_to_catalog.rb
  config/schedule.rb
  lib/tasks/c2m_tasks.rake
  lib/tasks/cv_tasks.rake
  lib/tasks/m2c_tasks.rake
Labels: needs review

#918 Remove unneeded explicit flush calls
  lib/tasks/c2m_tasks.rake
  lib/tasks/cv_tasks.rake
  lib/tasks/m2c_tasks.rake
Labels: needs review

#919 Cv by root by status
  .rubocop.yml
  README.md
  app/lib/audit/checksum.rb
  spec/lib/audit/checksum_spec.rb
Labels: needs review

#922 deploy: update shared_configs before migrating db
  config/deploy.rb
Labels: needs review

#924 Touchups to PC spec and some YARD
  app/models/preserved_copy.rb
  spec/models/preserved_copy_spec.rb
Labels: needs review

#931 Why isn't resque picking up the redis url?
  config/deploy.rb
Labels: needs review

#932 Monitor resque
  config/initializers/okcomputer.rb
Labels: needs review

#930 Pohandler spec refactor
  spec/services/preserved_object_handler_check_exist_spec.rb
  spec/services/preserved_object_handler_confirm_version_spec.rb
  spec/services/preserved_object_handler_create_spec.rb
  spec/services/preserved_object_handler_update_version_spec.rb
  spec/services/shared_examples_preserved_object_handler.rb
Labels: needs review

#935 Introduce resque-pool
  Gemfile
  Gemfile.lock
  config/resque-pool.yml
  lib/tasks/resque.rake
Labels: needs review

#929 DruidVersionZip logic for chunks
  app/models/druid_version_zip.rb
  spec/models/druid_version_zip_spec.rb
Labels: needs review

#915 C2A Logic. Checks the existence of s3 object and the md5.
  .rubocop.yml
  app/jobs/replicated_file_check_job.rb
  app/models/preserved_copy.rb
  app/models/preserved_object.rb
  spec/jobs/replicated_file_check_job_spec.rb
  spec/models/preserved_copy_spec.rb
Labels: needs review
